name:                kampong
version:             0.1.0.0
github:              "edwinhere/kampong"
license:             BSD3
author:              "Edwin Jose Palathinkal"
maintainer:          "edwinhere@gmail.com"
copyright:           "Edwin Jose Palathinkal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/edwinhere/kampong#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- text
- mtl
- transformers
- directory
- QuickCheck
- filepath
- time
- aeson
- hspec
- vector
- unordered-containers
- template-haskell
- process
- deepseq
- lens
- random
- array
- HUnit
- parsec
- network
- binary
- network-uri
- aeson-qq

library:
  source-dirs: src

executables:
  kampong-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kampong

tests:
  kampong-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kampong
    - hspec
